name: Release library as a PyPI wheel and sdist on tag

on:
  release:
    types: [created]

jobs:
  build-and-publish-to-pypi:
    name: Build and publish library to PyPI
    runs-on: ubuntu-24.04
    steps:
     - uses: actions/checkout@v4

     - name: Set up Python
       uses: actions/setup-python@v5
       with:
         python-version: 3.12

     - name: Install pypa/build and twine
       run: python -m pip install --user --upgrade build twine packaging pip setuptools

     - name: Build a binary wheel and a source tarball
       run: python -m build --sdist --wheel --outdir dist/ .

     - name: Check wheel and sdist with twine
       run: python -m twine check dist/*

     - name: Publish distribution to PyPI
       if: startsWith(github.ref, 'refs/tags')
       uses: pypa/gh-action-pypi-publish@release/v1
       with:
         password: ${{ secrets.PYPI_API_TOKEN }}
